# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: dk.fhir.ig.kl.tools.care
canonical: http://kl.dk/fhir/tools/care
name: municipalityTools
title: "Implementation Guide for værktøjsprojektet"
description: Danish municipalities implementation guide for værktøjsprojektet
status: draft
version: 0.3.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.dk.core:
    uri: https://hl7.dk/fhir/core
    version: 1.1.0
  dk.fhir.ig.kl.common.caresocial: current
copyrightYear: 2020+
releaseLabel: ci-build
date: 2020-10-30

publisher:
  name: Kommunernes landsforening
  url: http://kl.dk
  email: kl@kl.dk

jurisdiction: urn:iso:std:iso:3166#DNK "Denmark"

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
