# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.dk.fhir.ffinst
canonical: http://fhir.kl.dk/ffinst
name: KLFFinst
title: "Implementation Guide for fælles faglige instrumenter (FFInst)"
description: Danish municipalities implementation guide for FFInst
status: active # draft # active
version: 1.0.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.dk.core: 1.1.0
#    uri: https://hl7.dk/fhir/core
#    version: 1.1.0
  kl.dk.fhir.core: 1.2.0
  kl.dk.fhir.term: 1.0.0
copyrightYear: 2020+
releaseLabel: release # ci-build # release


publisher:
  name: Kommunernes landsforening
  url: http://kl.dk
  email: kl@kl.dk

jurisdiction: urn:iso:std:iso:3166#DNK "Denmark"

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
