# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: dk.fhir.ig.kl.tools.care
canonical: http://kl.dk/fhir/tools/care
name: municipalityTools
title: "Implementation Guide for værktøjsprojektet"
description: Danish municipalities implementation guide for værktøjsprojektet
status: draft
version: 0.1.1
fhirVersion: 4.0.1
dependencies:
  dk.fhir.ig.kl.common.caresocial: current
  dk.fhir.ig.dk-core: current    
copyrightYear: 2020+
releaseLabel: ci-build
date: 2020-10-30

publisher:
  name: Kommunernes landsforening
  url: http://kl.dk
  email: kl@kl.dk

jurisdiction: urn:iso:std:iso:3166#DNK "Denmark"

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
